In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('Books_Data.csv',sep=';')
df.head(15)

,index,Publishing Year,Book Name,Author,language_code,Author_Rating,Book_average_rating,Book_ratings_count,genre,gross sales,publisher revenue,sale price,sales rank,Publisher,units sold
0,0,1975.0,Beowulf,"Unknown, Seamus Heaney",en-US,Novice,3.42,155903.0,genre fiction,34160.00,20496.000,4.88,1.0,HarperCollins Publishers,7000.0
1,1,1987.0,Batman: Year One,"Frank Miller, David Mazzucchelli, Richmond Lew...",eng,Intermediate,4.23,145267.0,genre fiction,12437.50,7462.500,1.99,2.0,HarperCollins Publishers,6250.0
2,2,2015.0,Go Set a Watchman,Harper Lee,eng,Novice,3.31,138669.0,genre fiction,47795.00,28677.000,8.69,3.0,"Amazon Digital Services, Inc.",5500.0
3,3,2008.0,When You Are Engulfed in Flames,David Sedaris,en-US,Intermediate,4.04,150898.0,fiction,41250.00,24750.000,7.50,3.0,Hachette Book Group,5500.0
4,4,2011.0,Daughter of Smoke & Bone,Laini Taylor,eng,Intermediate,4.04,198283.0,genre fiction,37952.50,22771.500,7.99,4.0,Penguin Group (USA) LLC,4750.0
5,5,2015.0,Red Queen,Victoria Aveyard,eng,Intermediate,4.08,83354.0,genre fiction,19960.00,0.000,4.99,5.0,"Amazon Digital Services, Inc.",4000.0
6,6,2011.0,The Power of Habit,Charles Duhigg,eng,Intermediate,4.03,155977.0,genre fiction,27491.67,16495.002,6.99,6.0,HarperCollins Publishers,3933.0
7,7,1994.0,Midnight in the Garden of Good and Evil,John Berendt,eng,Intermediate,3.90,167997.0,nonfiction,26182.00,15709.200,6.89,8.0,Hachette Book Group,3800.0
8,8,2012.0,Hopeless,Colleen Hoover,eng,Intermediate,4.34,189938.0,genre fiction,26093.67,15656.202,6.99,9.0,HarperCollins Publishers,3733.0
9,9,1905.0,A Little Princess,"Frances Hodgson Burnett, Nancy Bond",eng,Intermediate,4.20,199872.0,genre fiction,23792.34,14275.404,6.49,10.0,Random House LLC,3666.0
10,10,2004.0,The Truth About Forever,Sarah Dessen,en-US,Intermediate,4.13,179415.0,genre fiction,17964.00,0.000,4.99,11.0,"Amazon Digital Services, Inc.",3600.0
11,11,1954.0,The horse and his boy,C.S. Lewis,eng,Intermediate,3.90,189671.0,fiction,21564.00,12938.400,5.99,11.0,Penguin Group (USA) LLC,3600.0
12,12,2010.0,Last Sacrifice,Richelle Mead,eng,Famous,4.42,206792.0,genre fiction,3431.34,0.000,0.99,13.0,"Amazon Digital Services, Inc.",3466.0
13,13,1935.0,Little House on the Prairie,"Laura Ingalls Wilder, Garth Williams",eng,Intermediate,4.18,195424.0,genre fiction,6897.34,4138.404,1.99,13.0,HarperCollins Publishers,3466.0
14,14,1922.0,The Velveteen Rabbit,"Margery Williams Bianco, William Nicholson",eng,Intermediate,4.29,173469.0,genre fiction,21797.82,13078.692,6.54,15.0,Random House LLC,3333.0

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df.columns= [col.strip().lower().replace(' ', '_') for col in df.columns]

print("\nUpdated column names:")
print(df.columns)

Updated column names:
Index(['index', 'publishing_year', 'book_name', 'author', 'language_code',
       'author_rating', 'book_average_rating', 'book_ratings_count', 'genre',
       'gross_sales', 'publisher_revenue', 'sale_price', 'sales_rank',
       'publisher', 'units_sold'],
      dtype='object')

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
empty_rows_count= df.isnull().sum().sum()
df.dropna(inplace=True)

print("\nNumber of rows with empty values removed:", empty_rows_count)

Number of rows with empty values removed: 101

In [11]:
import pandas as pd

df=pd.read_csv("Books_Data.csv",sep=";")
high_rating_df=df[df['Book_average_rating']>=4]
sorted_df=high_rating_df.sort_values(by='Book_average_rating',ascending=False)

top_10_books=sorted_df.head(10)
print(top_10_books)

     index  Publishing Year  \
331    331           2014.0
777    777           2016.0
479    479           1988.0
31      31           2010.0
249    249           1987.0
733    733           2015.0
433    433           1973.0
965    965           2000.0
153    153           2013.0
849    849           1986.0

                                             Book Name  \
331                                  Words of Radiance
777                           A Court of Mist and Fury
479  The Essential Calvin and Hobbes: A Calvin and ...
31                                    The Way of Kings
249                                  Calvin and Hobbes
733                                   Queen of Shadows
433               The Hobbit and The Lord of the Rings
965           A Storm of Swords: Part 2 Blood and Gold
153                                 The House of Hades
849                                  The Complete Maus

                           Author language_code Author_Rating  \
331             Brandon Sanderson           eng        Famous
777                 Sarah J. Maas           eng        Famous
479                Bill Watterson         en-US        Famous
31              Brandon Sanderson           eng        Famous
249  Bill Watterson, G.B. Trudeau         en-US        Famous
733                 Sarah J. Maas           eng        Famous
433                J.R.R. Tolkien           eng        Famous
965            George R.R. Martin           eng        Famous
153                  Rick Riordan           eng        Famous
849                Art Spiegelman         en-GB        Famous

     Book_average_rating  Book_ratings_count          genre  gross sales  \
331                 4.77             73572.0  genre fiction       741.52
777                 4.72            108384.0  genre fiction      1158.84
479                 4.65             93001.0  genre fiction       166.32
31                  4.64            144822.0  genre fiction      2178.00
249                 4.61            117788.0     nonfiction      1886.22
733                 4.60             99067.0  genre fiction       349.83
433                 4.59             90907.0  genre fiction       184.14
965                 4.56             54977.0  genre fiction       325.91
153                 4.54            159774.0     nonfiction       668.25
849                 4.53             76785.0     nonfiction       111.87

     publisher revenue  sale price  sales rank  \
331            444.912        2.99       354.0
777            695.304        9.99       900.0
479              0.000        0.99       530.0
31               0.000        0.99        32.0
249           1131.732        4.99       273.0
733            209.898        2.99       841.0
433            110.484        0.99       477.0
965              0.000        2.99      1140.0
153            400.950        0.99       165.0
849             67.122        0.99       994.0

                               Publisher   units sold
331              HarperCollins Publishers       248.0
777  Simon and Schuster Digital Sales Inc     28512.0
479        Amazon Digital Services,  Inc.      4536.0
31         Amazon Digital Services,  Inc.      2200.0
249               Penguin Group (USA) LLC       378.0
733                             Macmillan     33048.0
433        Amazon Digital Services,  Inc.      5022.0
965        Amazon Digital Services,  Inc.      4280.0
153        Amazon Digital Services,  Inc.       675.0
849        Amazon Digital Services,  Inc.      2862.0

In [12]:
import pandas as pd

df=pd.read_csv("Books_Data.csv", sep=";")

df['operatingCost']=df['gross sales']-df['publisher revenue']
df.drop(columns=['sales rank'], inplace=True)

print(df.head())

   index  Publishing Year                        Book Name  \
0      0           1975.0                          Beowulf
1      1           1987.0                 Batman: Year One
2      2           2015.0                Go Set a Watchman
3      3           2008.0  When You Are Engulfed in Flames
4      4           2011.0         Daughter of Smoke & Bone

                                              Author language_code  \
0                             Unknown, Seamus Heaney         en-US
1  Frank Miller, David Mazzucchelli, Richmond Lew...           eng
2                                         Harper Lee           eng
3                                      David Sedaris         en-US
4                                       Laini Taylor           eng

  Author_Rating  Book_average_rating  Book_ratings_count          genre  \
0        Novice                 3.42            155903.0  genre fiction
1  Intermediate                 4.23            145267.0  genre fiction
2        Novice                 3.31            138669.0  genre fiction
3  Intermediate                 4.04            150898.0        fiction
4  Intermediate                 4.04            198283.0  genre fiction

   gross sales  publisher revenue  sale price                      Publisher   \
0      34160.0            20496.0        4.88        HarperCollins Publishers
1      12437.5             7462.5        1.99        HarperCollins Publishers
2      47795.0            28677.0        8.69  Amazon Digital Services,  Inc.
3      41250.0            24750.0        7.50             Hachette Book Group
4      37952.5            22771.5        7.99         Penguin Group (USA) LLC

   units sold  operatingCost
0      7000.0        13664.0
1      6250.0         4975.0
2      5500.0        19118.0
3      5500.0        16500.0
4      4750.0        15181.0

In [13]:

mean_gross_sales = df['gross sales'].mean()
median_gross_sales = df['gross sales'].median()
std_dev_gross_sales = df['gross sales'].std()

print("Mean gross sales:", mean_gross_sales)
print("Median gross sales:", median_gross_sales)
print("Standard deviation of gross sales:", std_dev_gross_sales)

Mean gross sales: 1856.755383895131
Median gross sales: 806.25
Standard deviation of gross sales: 3940.595148274063

In [14]:
df['Publishing Year']=df['Publishing Year'].astype(str).str.split('.').str[0]

incorrect_dates_index=df[df['Publishing Year'].str.contains('[0-9]')].index
df.drop(index=incorrect_dates_index, inplace=True)

print(df.head())

     index Publishing Year Book Name                     Author language_code  \
445    445             nan       NaN  Robert Kapilow, Dr. Seuss           NaN

    Author_Rating  Book_average_rating  Book_ratings_count       genre  \
445        Famous                 4.44             90574.0  nonfiction

     gross sales  publisher revenue  sale price           Publisher   \
445       532.22            319.332        2.99  Hachette Book Group

     units sold  operatingCost
445      4806.0        212.888